module.exports = {
	tabWidth: 2,
	useTabs: false,
	semi: true,
	singleQuote: true,
	bracketSpacing: true,
	trailingComma: 'es5',
	printWidth: 80,
	quoteProps: 'as-needed',
	bracketSameLine: false,
	arrowParens: 'always',
	htmlWhitespaceSensitivity: 'css',
	endOfLine: 'lf',
	embeddedLanguageFormatting: 'auto',
};
